Error keeping the connection alive: Error: Server shutdown in progress
    at Packet.asError (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/packets/packet.js:740:17)
    at Query.execute (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/base/connection.js:475:34)
    at PacketParser.onPacket (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/base/connection.js:93:12)
    at PacketParser.executeStart (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/base/connection.js:100:25)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_SERVER_SHUTDOWN',
  errno: 1053,
  sqlState: '08S01',
  sqlMessage: 'Server shutdown in progress',
  sql: 'SELECT 1'
}
Error connecting to the database: AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1139:18)
    at afterConnectMultiple (node:net:1712:7)
/home/ije17622/codemitra.dmifotech.com/server/config/db.js:30
      throw err;
      ^

AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1139:18)
    at afterConnectMultiple (node:net:1712:7) {
  code: 'ECONNREFUSED',
  fatal: true,
  [errors]: [
    Error: connect ECONNREFUSED ::1:3306
        at createConnectionError (node:net:1675:14)
        at afterConnectMultiple (node:net:1705:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 3306
    },
    Error: connect ECONNREFUSED 127.0.0.1:3306
        at createConnectionError (node:net:1675:14)
        at afterConnectMultiple (node:net:1705:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 3306
    }
  ]
}

Node.js v22.13.1
Error keeping the connection alive: Error: Server shutdown in progress
    at Packet.asError (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/packets/packet.js:740:17)
    at Query.execute (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/base/connection.js:475:34)
    at PacketParser.onPacket (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/base/connection.js:93:12)
    at PacketParser.executeStart (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/base/connection.js:100:25)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_SERVER_SHUTDOWN',
  errno: 1053,
  sqlState: '08S01',
  sqlMessage: 'Server shutdown in progress',
  sql: 'SELECT 1'
}
Error connecting to the database: AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1139:18)
    at afterConnectMultiple (node:net:1712:7)
/home/ije17622/codemitra.dmifotech.com/server/config/db.js:30
      throw err;
      ^

AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1139:18)
    at afterConnectMultiple (node:net:1712:7) {
  code: 'ECONNREFUSED',
  fatal: true,
  [errors]: [
    Error: connect ECONNREFUSED ::1:3306
        at createConnectionError (node:net:1675:14)
        at afterConnectMultiple (node:net:1705:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 3306
    },
    Error: connect ECONNREFUSED 127.0.0.1:3306
        at createConnectionError (node:net:1675:14)
        at afterConnectMultiple (node:net:1705:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 3306
    }
  ]
}

Node.js v22.13.1
Error connecting to the database: AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1139:18)
    at afterConnectMultiple (node:net:1712:7)
/home/ije17622/codemitra.dmifotech.com/server/config/db.js:30
      throw err;
      ^

AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1139:18)
    at afterConnectMultiple (node:net:1712:7) {
  code: 'ECONNREFUSED',
  fatal: true,
  [errors]: [
    Error: connect ECONNREFUSED ::1:3306
        at createConnectionError (node:net:1675:14)
        at afterConnectMultiple (node:net:1705:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 3306
    },
    Error: connect ECONNREFUSED 127.0.0.1:3306
        at createConnectionError (node:net:1675:14)
        at afterConnectMultiple (node:net:1705:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 3306
    }
  ]
}

Node.js v22.13.1
Error keeping the connection alive: Error: Server shutdown in progress
    at Packet.asError (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/packets/packet.js:740:17)
    at Query.execute (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/base/connection.js:475:34)
    at PacketParser.onPacket (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/base/connection.js:93:12)
    at PacketParser.executeStart (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/ije17622/nodevenv/codemitra.dmifotech.com/server/22/lib/node_modules/mysql2/lib/base/connection.js:100:25)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_SERVER_SHUTDOWN',
  errno: 1053,
  sqlState: '08S01',
  sqlMessage: 'Server shutdown in progress',
  sql: 'SELECT 1'
}
Error connecting to the database: AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1139:18)
    at afterConnectMultiple (node:net:1712:7)
/home/ije17622/codemitra.dmifotech.com/server/config/db.js:30
      throw err;
      ^

AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1139:18)
    at afterConnectMultiple (node:net:1712:7) {
  code: 'ECONNREFUSED',
  fatal: true,
  [errors]: [
    Error: connect ECONNREFUSED ::1:3306
        at createConnectionError (node:net:1675:14)
        at afterConnectMultiple (node:net:1705:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 3306
    },
    Error: connect ECONNREFUSED 127.0.0.1:3306
        at createConnectionError (node:net:1675:14)
        at afterConnectMultiple (node:net:1705:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 3306
    }
  ]
}

Node.js v22.13.1
Error connecting to the database: AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1139:18)
    at afterConnectMultiple (node:net:1712:7)
/home/ije17622/codemitra.dmifotech.com/server/config/db.js:30
      throw err;
      ^

AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1139:18)
    at afterConnectMultiple (node:net:1712:7) {
  code: 'ECONNREFUSED',
  fatal: true,
  [errors]: [
    Error: connect ECONNREFUSED ::1:3306
        at createConnectionError (node:net:1675:14)
        at afterConnectMultiple (node:net:1705:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 3306
    },
    Error: connect ECONNREFUSED 127.0.0.1:3306
        at createConnectionError (node:net:1675:14)
        at afterConnectMultiple (node:net:1705:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 3306
    }
  ]
}

Node.js v22.13.1
/home/ije17622/codemitra.dmifotech.com/server/index.js:7
const cors = require("cors");
      ^

SyntaxError: Identifier 'cors' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Module._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)

Node.js v22.13.1
/home/ije17622/codemitra.dmifotech.com/server/index.js:7
const cors = require("cors");
      ^

SyntaxError: Identifier 'cors' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Module._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)

Node.js v22.13.1
/home/ije17622/codemitra.dmifotech.com/server/index.js:7
const cors = require("cors");
      ^

SyntaxError: Identifier 'cors' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Module._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)

Node.js v22.13.1
/home/ije17622/codemitra.dmifotech.com/server/index.js:7
const cors = require("cors");
      ^

SyntaxError: Identifier 'cors' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Module._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)

Node.js v22.13.1
/home/ije17622/codemitra.dmifotech.com/server/index.js:7
const cors = require("cors");
      ^

SyntaxError: Identifier 'cors' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Module._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)

Node.js v22.13.1
/home/ije17622/codemitra.dmifotech.com/server/index.js:7
const cors = require("cors");
      ^

SyntaxError: Identifier 'cors' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Module._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)

Node.js v22.13.1
/home/ije17622/codemitra.dmifotech.com/server/index.js:7
const cors = require("cors");
      ^

SyntaxError: Identifier 'cors' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Module._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)

Node.js v22.13.1
/home/ije17622/codemitra.dmifotech.com/server/index.js:7
const cors = require("cors");
      ^

SyntaxError: Identifier 'cors' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Module._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)

Node.js v22.13.1
